#+STARTUP: nofold

Rolling list of things to do
* TODO
  - [-] Export user names from the comment table. :Mo:
    - [ ] Test that the export and re-imports works on windows.
      * Tested version 0.9.3 works for both windows and linux with
        Edit mode but not the original questionnaire. 
      * Tested version 0.9.4, doesn't work for either windows or
        linux. Shifting of worksheet name, when sheet doesn't have a
        comment. Possible solution is to add dummy comments to every sheet.
      * Tested version 0.9.2, works perfectly with Linux and
        patch, not with windows.
    - [X] Test patching ~xlrd~ on windows
      - Comments work with xlrd 0.9.3 without patching only in Edit mode.
      - Code only inserts user name in both field in EDU_FTN97. 
  - [X] Erase the Inclusion table :Os:
  - [ ] Complete the Gui user guide :Mo:
    - Missing :Os: import for what type of pre-processing checks. 
  - [X] Add default export folder in the GUI :Mo:
  - [X] Put confirmation statements after each step :Mo: :Os:
  - [X] Add a scroller the Status label.
  - [ ] Code documentation.
  - [ ] Trailing.
  - [X] Pre-procession to check all errors before stopping the
    program. Currently once it find an error it stops.
  - [X] List all pre-processing steps. :Os:
  - [X] Cell comments should have time stamp to when they are inserted.
  - [ ] List all pre-processing steps. :Os:
  - [X] Cell comments should have time stamp to when they are inserted.
    - We can follow the following convention: Username(TimeDate):
      comment data, and then I can till users to not edit.
    - Differed for later
      Username(TimeDate section). :Os: :Mo:
  - [X] properly name log file :Os:
  - [ ] Create the Readme file :Mo:
  - [X] Format error :Os:
    

* Example exit with xlrd 0.9.4:
Date: 08/04/15
Questionnaire path: /home/oscar/RMS/Regional_Questionnaire_Asia_Final_v7_locked_LAOS.xlsx
All the checks passes. QUESTIONNAIRE CAN BE PROCESSED
Front Page:dict_keys([(13, 20)])
Respondent Information:dict_keys([(15, 11), (26, 11), (17, 9)])
Administrative divisions:dict_keys([(18, 13)])
Policy information:dict_keys([(37, 23)])
Pupils:dict_keys([(18, 49)])
Teachers ISCED 1:dict_keys([])
Teachers ISCED 2:dict_keys([])
Teachers ISCED 3:dict_keys([])
Teachers ISCED 23:dict_keys([])
Checking sheet:dict_keys([])
Changes log:dict_keys([])
Unlocked areas:dict_keys([])
